### ISSUE TITLE
Summarize Filtered Data

### ISSUE THREAD

**Issue by bentz0705** [kirixresearch/strata#2]
When a file is filtered and then summarized the result given is the same as when the unfiltered file is summarized. The result should only be on the filtered records. To recreate, use the following steps:

1. Open the attached file Sample in Strata.
2. Right click the Amount field and click Summarize.
3. Save (untitled) as Unfiltered.
4. Filter Sample on Claim.
5. Right click the Amount field and click Summarize.
6. Save (untitled) as Filtered.

Notice that the values in Filtered are the same as Unfiltered. The values in Filtered that should be different are:

- Maximum: 0.00
- Sum_Amount: 0.00
- Average: 0.00
- Total Count: 1

[Sample.zip](https://github.com/kirixresearch/strata/files/10327786/Sample.zip)

Version 5.0.0 of Kirix Strata

**Comment by biwillia** [comment]
This has been fixed and will be included in the upcoming dot-release. Thanks for the report.
