### ISSUE TITLE
Export to MS Excel and MS Access doesn’t work

### ISSUE THREAD

**Issue by natetrek** [kirixresearch/strata#3]
The file export option for MS Excel and MS Access no longer work in version 5.0.0. 

When attempting to export file in an Excel or Access format, Strata displays the following error message: "Kirix Strata is missing a software component. To correct this problem, please reinstall Kirix Strata." However, reinstalling Kirix Strata does not fix this issue.

![kirix-excel-export-issue](https://user-images.githubusercontent.com/25989785/213640144-1b47126b-44c8-4611-93ac-818acbefc460.png)

To replicate this issue, do the following:

* Select "Export" from the File menu
* Select "Microsoft Excel File" or "Microsoft Access File" from the "Export As" dropdown option
* Click "Next" to advance to the next page of the dialog
* Add a file to the list of files to export
* Click "Finish"

**Comment by biwillia** [comment]
Fixed.
