### ISSUE TITLE
Browsing and importing CSV files from a folder connection no longer works

### ISSUE THREAD

**Issue by natetrek** [kirixresearch/strata#5]
It is no longer possible to open and import CSV files from a connection to a folder in version 5.0.0.

After creating a connection to a folder, Strata lists CSV files in this folder in the Project Panel but will not open them when double-clicking on them. In addition, it is no longer possible to import a batch of CSV file by selecting them in a connected folder and dragging them into a local folder in the Project Panel. Earlier versions of Strata supported both of these operations, which were extremely useful to have -- it was super easy to select and view different CSV files this way and also very easy to import multiple CSV files at once.

![kirix-strata-csv-import-from-connection-01](https://user-images.githubusercontent.com/25989785/215634288-1717e882-e14b-479a-ba3c-dc760fcaecdf.png)
![kirix-strata-csv-import-from-connection-02](https://user-images.githubusercontent.com/25989785/215634306-0a84e620-f926-4cb3-8b06-6a55db9001ad.png)

To replicate this issue, do the following:

* Select "Create Connection" from the File menu
* Browse for a folder containing CSV files
* Click "Connect" to create a connection to this folder
* Open the connected folder in the Project Panel
* Double-click on one of the CSV files in the folder
* Right-click on one of the CSV files and select "Open" from the right-click menu
* Select a group of CSV files and drag and drop them into a different, local folder in the Project Panel

**Comment by biwillia** [comment]
Double-click open is now fixed. I will also take a look at fixing drag import soon and will leave this issue open until it's fixed.

**Comment by biwillia** [comment]
Fixed
